rishtas = [
    # Female Rishtas (50)
    {
        "name": "Fatima",
        "age": 20,
        "gender": "Female",
        "profession": "Engineer",
        "education": "B.E",
    },
    {
        "name": "Zainab",
        "age": 19,
        "gender": "Female",
        "profession": "Doctor",
        "education": "MBBS",
    },
    {
        "name": "Hira",
        "age": 22,
        "gender": "Female",
        "profession": "Teacher",
        "education": "MA English",
    },
    {
        "name": "Sara",
        "age": 23,
        "gender": "Female",
        "profession": "Lawyer",
        "education": "LLB",
    },
    {
        "name": "Mehwish",
        "age": 29,
        "gender": "Female",
        "profession": "HR Manager",
        "education": "MBA",
    },
    {
        "name": "Laiba",
        "age": 22,
        "gender": "Female",
        "profession": "Pharmacist",
        "education": "PharmD",
    },
    {
        "name": "Kiran",
        "age": 28,
        "gender": "Female",
        "profession": "Lecturer",
        "education": "MSc Physics",
    },
    {
        "name": "Mariam",
        "age": 30,
        "gender": "Female",
        "profession": "Chartered Accountant",
        "education": "CA",
    },
    {
        "name": "Sana",
        "age": 25,
        "gender": "Female",
        "profession": "Nutritionist",
        "education": "BS Nutrition",
    },
    {
        "name": "Amna",
        "age": 26,
        "gender": "Female",
        "profession": "Banker",
        "education": "BBA",
    },
    {
        "name": "Nimra",
        "age": 27,
        "gender": "Female",
        "profession": "Artist",
        "education": "Fine Arts",
    },
    {
        "name": "Tania",
        "age": 24,
        "gender": "Female",
        "profession": "Software Engineer",
        "education": "BSCS",
    },
    {
        "name": "Uzma",
        "age": 28,
        "gender": "Female",
        "profession": "Psychologist",
        "education": "MSc Psychology",
    },
    {
        "name": "Areeba",
        "age": 23,
        "gender": "Female",
        "profession": "Social Worker",
        "education": "BA Sociology",
    },
    {
        "name": "Eman",
        "age": 29,
        "gender": "Female",
        "profession": "Dentist",
        "education": "BDS",
    },
    {
        "name": "Iqra",
        "age": 24,
        "gender": "Female",
        "profession": "Nurse",
        "education": "BSc Nursing",
    },
    {
        "name": "Anam",
        "age": 25,
        "gender": "Female",
        "profession": "Fashion Designer",
        "education": "BFD",
    },
    {
        "name": "Shazia",
        "age": 28,
        "gender": "Female",
        "profession": "Journalist",
        "education": "Mass Comm",
    },
    {
        "name": "Nazia",
        "age": 27,
        "gender": "Female",
        "profession": "Software Developer",
        "education": "BSSE",
    },
    {
        "name": "Huma",
        "age": 26,
        "gender": "Female",
        "profession": "Interior Designer",
        "education": "BID",
    },
    {
        "name": "Noor",
        "age": 22,
        "gender": "Female",
        "profession": "Animator",
        "education": "BS Animation",
    },
    {
        "name": "Yusra",
        "age": 29,
        "gender": "Female",
        "profession": "Content Writer",
        "education": "BA English",
    },
    {
        "name": "Sadia",
        "age": 30,
        "gender": "Female",
        "profession": "Economist",
        "education": "MSc Economics",
    },
    {
        "name": "Hafsa",
        "age": 24,
        "gender": "Female",
        "profession": "Scientist",
        "education": "MPhil Chemistry",
    },
    {
        "name": "Aiman",
        "age": 25,
        "gender": "Female",
        "profession": "Environmentalist",
        "education": "MS Env Sci",
    },
    {
        "name": "Lubna",
        "age": 28,
        "gender": "Female",
        "profession": "Mathematician",
        "education": "MSc Math",
    },
    {
        "name": "Iqbal",
        "age": 27,
        "gender": "Female",
        "profession": "Software Tester",
        "education": "BSCS",
    },
    {
        "name": "Shaista",
        "age": 24,
        "gender": "Female",
        "profession": "Architect",
        "education": "B.Arch",
    },
    {
        "name": "Humaira",
        "age": 29,
        "gender": "Female",
        "profession": "Digital Marketer",
        "education": "BBA Marketing",
    },
    {
        "name": "Aqsa",
        "age": 26,
        "gender": "Female",
        "profession": "Librarian",
        "education": "MLIS",
    },
    {
        "name": "Aaliya",
        "age": 25,
        "gender": "Female",
        "profession": "Photographer",
        "education": "BFA",
    },
    {
        "name": "Rabia",
        "age": 28,
        "gender": "Female",
        "profession": "Data Analyst",
        "education": "BS Data Science",
    },
    {
        "name": "Kinza",
        "age": 30,
        "gender": "Female",
        "profession": "Statistician",
        "education": "MS Statistics",
    },
    {
        "name": "Fiza",
        "age": 23,
        "gender": "Female",
        "profession": "Translator",
        "education": "MA Urdu",
    },
    {
        "name": "Neha",
        "age": 24,
        "gender": "Female",
        "profession": "Host",
        "education": "BS Media",
    },
    {
        "name": "Bushra",
        "age": 25,
        "gender": "Female",
        "profession": "Geologist",
        "education": "BS Geology",
    },
    {
        "name": "Sahar",
        "age": 29,
        "gender": "Female",
        "profession": "UX Designer",
        "education": "BS HCI",
    },
    {
        "name": "Reema",
        "age": 26,
        "gender": "Female",
        "profession": "Makeup Artist",
        "education": "Diploma Cosmetology",
    },
    {
        "name": "Asma",
        "age": 30,
        "gender": "Female",
        "profession": "Air Hostess",
        "education": "FA",
    },
    {
        "name": "Zoya",
        "age": 28,
        "gender": "Female",
        "profession": "Chef",
        "education": "Diploma Culinary",
    },
    {
        "name": "Nadia",
        "age": 29,
        "gender": "Female",
        "profession": "PR Officer",
        "education": "BSPR",
    },
    {
        "name": "Komal",
        "age": 27,
        "gender": "Female",
        "profession": "Counselor",
        "education": "MSc Psychology",
    },
    {
        "name": "Rida",
        "age": 26,
        "gender": "Female",
        "profession": "SEO Specialist",
        "education": "BS IT",
    },
    {
        "name": "Javeria",
        "age": 25,
        "gender": "Female",
        "profession": "Researcher",
        "education": "MPhil Biology",
    },
    {
        "name": "Shumaila",
        "age": 29,
        "gender": "Female",
        "profession": "Lecturer",
        "education": "M.Ed",
    },
    {
        "name": "Haleema",
        "age": 24,
        "gender": "Female",
        "profession": "Accountant",
        "education": "B.Com",
    },
    {
        "name": "Najma",
        "age": 30,
        "gender": "Female",
        "profession": "Fitness Coach",
        "education": "BS Sports Sci",
    },
    {
        "name": "Rukhsar",
        "age": 28,
        "gender": "Female",
        "profession": "Biochemist",
        "education": "BS Biochemistry",
    },
    {
        "name": "Farah",
        "age": 27,
        "gender": "Female",
        "profession": "QA Engineer",
        "education": "BSSE",
    },
    # Male Rishtas (50)
    {
        "name": "Ali",
        "age": 28,
        "gender": "Male",
        "profession": "Software Engineer",
        "education": "BSCS",
    },
    {
        "name": "Ahmed",
        "age": 30,
        "gender": "Male",
        "profession": "Banker",
        "education": "MBA",
    },
    {
        "name": "Usman",
        "age": 27,
        "gender": "Male",
        "profession": "Doctor",
        "education": "MBBS",
    },
    {
        "name": "Hamza",
        "age": 26,
        "gender": "Male",
        "profession": "Lawyer",
        "education": "LLB",
    },
    {
        "name": "Zeeshan",
        "age": 29,
        "gender": "Male",
        "profession": "Civil Engineer",
        "education": "B.E",
    },
    {
        "name": "Talha",
        "age": 28,
        "gender": "Male",
        "profession": "Accountant",
        "education": "ACCA",
    },
    {
        "name": "Noman",
        "age": 30,
        "gender": "Male",
        "profession": "Professor",
        "education": "PhD",
    },
    {
        "name": "Danish",
        "age": 25,
        "gender": "Male",
        "profession": "Pharmacist",
        "education": "PharmD",
    },
    {
        "name": "Bilal",
        "age": 26,
        "gender": "Male",
        "profession": "Businessman",
        "education": "BBA",
    },
    {
        "name": "Salman",
        "age": 27,
        "gender": "Male",
        "profession": "Mechanical Engineer",
        "education": "BSME",
    },
    {
        "name": "Asad",
        "age": 28,
        "gender": "Male",
        "profession": "Pilot",
        "education": "Aviation",
    },
    {
        "name": "Rehan",
        "age": 29,
        "gender": "Male",
        "profession": "Marketing Manager",
        "education": "MBA",
    },
    {
        "name": "Saad",
        "age": 30,
        "gender": "Male",
        "profession": "HR Officer",
        "education": "BBA",
    },
    {
        "name": "Yasir",
        "age": 26,
        "gender": "Male",
        "profession": "Electrical Engineer",
        "education": "BEE",
    },
    {
        "name": "Owais",
        "age": 25,
        "gender": "Male",
        "profession": "Civil Servant",
        "education": "CSS",
    },
    {
        "name": "Rizwan",
        "age": 27,
        "gender": "Male",
        "profession": "Graphic Designer",
        "education": "BFA",
    },
    {
        "name": "Shahzaib",
        "age": 28,
        "gender": "Male",
        "profession": "Journalist",
        "education": "Mass Comm",
    },
    {
        "name": "Moiz",
        "age": 29,
        "gender": "Male",
        "profession": "Economist",
        "education": "MSc Economics",
    },
    {
        "name": "Waqas",
        "age": 30,
        "gender": "Male",
        "profession": "Psychologist",
        "education": "MSc Psychology",
    },
    {
        "name": "Fahad",
        "age": 24,
        "gender": "Male",
        "profession": "Data Scientist",
        "education": "BS Data Science",
    },
    {
        "name": "Tariq",
        "age": 25,
        "gender": "Male",
        "profession": "Lab Technician",
        "education": "DMLT",
    },
    {
        "name": "Adeel",
        "age": 26,
        "gender": "Male",
        "profession": "Content Writer",
        "education": "BA English",
    },
    {
        "name": "Hassan",
        "age": 27,
        "gender": "Male",
        "profession": "Architect",
        "education": "B.Arch",
    },
    {
        "name": "Imran",
        "age": 28,
        "gender": "Male",
        "profession": "Auditor",
        "education": "CA",
    },
    {
        "name": "Zubair",
        "age": 29,
        "gender": "Male",
        "profession": "Digital Marketer",
        "education": "BS Marketing",
    },
    {
        "name": "Shahid",
        "age": 30,
        "gender": "Male",
        "profession": "Fitness Trainer",
        "education": "BS Sports Sci",
    },
    {
        "name": "Naveed",
        "age": 26,
        "gender": "Male",
        "profession": "Chef",
        "education": "Diploma Culinary",
    },
    {
        "name": "Arslan",
        "age": 27,
        "gender": "Male",
        "profession": "Librarian",
        "education": "MLIS",
    },
    {
        "name": "Umar",
        "age": 28,
        "gender": "Male",
        "profession": "Teacher",
        "education": "MA Urdu",
    },
    {
        "name": "Ahsan",
        "age": 29,
        "gender": "Male",
        "profession": "Engineer",
        "education": "B.E",
    },
    {
        "name": "Jawad",
        "age": 30,
        "gender": "Male",
        "profession": "Network Admin",
        "education": "BS IT",
    },
    {
        "name": "Ammar",
        "age": 25,
        "gender": "Male",
        "profession": "AI Developer",
        "education": "BSCS",
    },
    {
        "name": "Junaid",
        "age": 26,
        "gender": "Male",
        "profession": "Video Editor",
        "education": "BFA",
    },
    {
        "name": "Kashif",
        "age": 27,
        "gender": "Male",
        "profession": "Systems Analyst",
        "education": "BSSE",
    },
    {
        "name": "Shayan",
        "age": 28,
        "gender": "Male",
        "profession": "Researcher",
        "education": "MPhil Physics",
    },
    {
        "name": "Rauf",
        "age": 29,
        "gender": "Male",
        "profession": "Game Developer",
        "education": "BS Game Dev",
    },
    {
        "name": "Basit",
        "age": 30,
        "gender": "Male",
        "profession": "Cybersecurity Expert",
        "education": "MS CyberSec",
    },
    {
        "name": "Kamran",
        "age": 26,
        "gender": "Male",
        "profession": "UX Designer",
        "education": "BS HCI",
    },
    {
        "name": "Irfan",
        "age": 27,
        "gender": "Male",
        "profession": "Translator",
        "education": "MA Arabic",
    },
    {
        "name": "Qasim",
        "age": 28,
        "gender": "Male",
        "profession": "Statistician",
        "education": "MS Stats",
    },
    {
        "name": "Waqar",
        "age": 29,
        "gender": "Male",
        "profession": "Biotechnologist",
        "education": "BS Biotech",
    },
    {
        "name": "Azhar",
        "age": 30,
        "gender": "Male",
        "profession": "Operations Manager",
        "education": "MBA",
    },
    {
        "name": "Naeem",
        "age": 25,
        "gender": "Male",
        "profession": "SEO Specialist",
        "education": "BS IT",
    },
    {
        "name": "Taimoor",
        "age": 26,
        "gender": "Male",
        "profession": "Software Tester",
        "education": "BSSE",
    },
    {
        "name": "Omar",
        "age": 27,
        "gender": "Male",
        "profession": "Web Developer",
        "education": "BS Web Dev",
    },
    {
        "name": "Haroon",
        "age": 28,
        "gender": "Male",
        "profession": "Statistician",
        "education": "MSc Math",
    },
    {
        "name": "Faizan",
        "age": 29,
        "gender": "Male",
        "profession": "DevOps Engineer",
        "education": "BSCS",
    },
    {
        "name": "Shabbir",
        "age": 30,
        "gender": "Male",
        "profession": "Political Analyst",
        "education": "BS Political Sci",
    },
]
