rishtas = [
    # Female Rishtas (100)
    {
        "name": "Amna Jawed",
        "age": 18,
        "gender": "Female",
        "profession": "Designer",
        "education": "HSC",
        "location": "Karachi",
    },
    {
        "name": "Fatima",
        "age": 20,
        "gender": "Female",
        "profession": "Engineer",
        "education": "B.E",
        "location": "Karachi",
    },
    {
        "name": "Zainab",
        "age": 19,
        "gender": "Female",
        "profession": "Doctor",
        "education": "MBBS",
        "location": "Lahore",
    },
    {
        "name": "Hira",
        "age": 22,
        "gender": "Female",
        "profession": "Teacher",
        "education": "MA English",
        "location": "Islamabad",
    },
    {
        "name": "Sara",
        "age": 23,
        "gender": "Female",
        "profession": "Lawyer",
        "education": "LLB",
        "location": "Rawalpindi",
    },
    {
        "name": "Mehwish",
        "age": 29,
        "gender": "Female",
        "profession": "HR Manager",
        "education": "MBA",
        "location": "Faisalabad",
    },
    {
        "name": "Laiba",
        "age": 22,
        "gender": "Female",
        "profession": "Pharmacist",
        "education": "PharmD",
        "location": "Peshawar",
    },
    {
        "name": "Kiran",
        "age": 28,
        "gender": "Female",
        "profession": "Lecturer",
        "education": "MSc Physics",
        "location": "Karachi",
    },
    {
        "name": "Mariam",
        "age": 30,
        "gender": "Female",
        "profession": "Chartered Accountant",
        "education": "CA",
        "location": "Lahore",
    },
    {
        "name": "Sana",
        "age": 25,
        "gender": "Female",
        "profession": "Nutritionist",
        "education": "BS Nutrition",
        "location": "Islamabad",
    },
    {
        "name": "Amna",
        "age": 26,
        "gender": "Female",
        "profession": "Banker",
        "education": "BBA",
        "location": "Rawalpindi",
    },
    {
        "name": "Nimra",
        "age": 27,
        "gender": "Female",
        "profession": "Artist",
        "education": "Fine Arts",
        "location": "Faisalabad",
    },
    {
        "name": "Tania",
        "age": 24,
        "gender": "Female",
        "profession": "Software Engineer",
        "education": "BSCS",
        "location": "Peshawar",
    },
    {
        "name": "Uzma",
        "age": 28,
        "gender": "Female",
        "profession": "Psychologist",
        "education": "MSc Psychology",
        "location": "Karachi",
    },
    {
        "name": "Areeba",
        "age": 23,
        "gender": "Female",
        "profession": "Social Worker",
        "education": "BA Sociology",
        "location": "Lahore",
    },
    {
        "name": "Eman",
        "age": 29,
        "gender": "Female",
        "profession": "Dentist",
        "education": "BDS",
        "location": "Islamabad",
    },
    {
        "name": "Iqra",
        "age": 24,
        "gender": "Female",
        "profession": "Nurse",
        "education": "BSc Nursing",
        "location": "Rawalpindi",
    },
    {
        "name": "Anam",
        "age": 25,
        "gender": "Female",
        "profession": "Fashion Designer",
        "education": "BFD",
        "location": "Faisalabad",
    },
    {
        "name": "Shazia",
        "age": 28,
        "gender": "Female",
        "profession": "Journalist",
        "education": "Mass Comm",
        "location": "Peshawar",
    },
    {
        "name": "Nazia",
        "age": 27,
        "gender": "Female",
        "profession": "Software Developer",
        "education": "BSSE",
        "location": "Karachi",
    },
    {
        "name": "Huma",
        "age": 26,
        "gender": "Female",
        "profession": "Interior Designer",
        "education": "BID",
        "location": "Lahore",
    },
    {
        "name": "Noor",
        "age": 22,
        "gender": "Female",
        "profession": "Animator",
        "education": "BS Animation",
        "location": "Islamabad",
    },
    {
        "name": "Yusra",
        "age": 29,
        "gender": "Female",
        "profession": "Content Writer",
        "education": "BA English",
        "location": "Rawalpindi",
    },
    {
        "name": "Sadia",
        "age": 30,
        "gender": "Female",
        "profession": "Economist",
        "education": "MSc Economics",
        "location": "Faisalabad",
    },
    {
        "name": "Hafsa",
        "age": 24,
        "gender": "Female",
        "profession": "Scientist",
        "education": "MPhil Chemistry",
        "location": "Peshawar",
    },
    {
        "name": "Aiman",
        "age": 25,
        "gender": "Female",
        "profession": "Environmentalist",
        "education": "MS Env Sci",
        "location": "Karachi",
    },
    {
        "name": "Lubna",
        "age": 28,
        "gender": "Female",
        "profession": "Mathematician",
        "education": "MSc Math",
        "location": "Lahore",
    },
    {
        "name": "Iqbal",
        "age": 27,
        "gender": "Female",
        "profession": "Software Tester",
        "education": "BSCS",
        "location": "Islamabad",
    },
    {
        "name": "Shaista",
        "age": 24,
        "gender": "Female",
        "profession": "Architect",
        "education": "B.Arch",
        "location": "Rawalpindi",
    },
    {
        "name": "Humaira",
        "age": 29,
        "gender": "Female",
        "profession": "Digital Marketer",
        "education": "BBA Marketing",
        "location": "Faisalabad",
    },
    {
        "name": "Aqsa",
        "age": 26,
        "gender": "Female",
        "profession": "Librarian",
        "education": "MLIS",
        "location": "Peshawar",
    },
    {
        "name": "Aaliya",
        "age": 25,
        "gender": "Female",
        "profession": "Photographer",
        "education": "BFA",
        "location": "Karachi",
    },
    {
        "name": "Rabia",
        "age": 28,
        "gender": "Female",
        "profession": "Data Analyst",
        "education": "BS Data Science",
        "location": "Lahore",
    },
    {
        "name": "Kinza",
        "age": 30,
        "gender": "Female",
        "profession": "Statistician",
        "education": "MS Statistics",
        "location": "Islamabad",
    },
    {
        "name": "Fiza",
        "age": 23,
        "gender": "Female",
        "profession": "Translator",
        "education": "MA Urdu",
        "location": "Rawalpindi",
    },
    {
        "name": "Neha",
        "age": 24,
        "gender": "Female",
        "profession": "Host",
        "education": "BS Media",
        "location": "Faisalabad",
    },
    {
        "name": "Bushra",
        "age": 25,
        "gender": "Female",
        "profession": "Geologist",
        "education": "BS Geology",
        "location": "Peshawar",
    },
    {
        "name": "Sahar",
        "age": 29,
        "gender": "Female",
        "profession": "UX Designer",
        "education": "BS HCI",
        "location": "Karachi",
    },
    {
        "name": "Reema",
        "age": 26,
        "gender": "Female",
        "profession": "Makeup Artist",
        "education": "Diploma Cosmetology",
        "location": "Lahore",
    },
    {
        "name": "Asma",
        "age": 30,
        "gender": "Female",
        "profession": "Air Hostess",
        "education": "FA",
        "location": "Islamabad",
    },
    {
        "name": "Zoya",
        "age": 28,
        "gender": "Female",
        "profession": "Chef",
        "education": "Diploma Culinary",
        "location": "Rawalpindi",
    },
    {
        "name": "Nadia",
        "age": 29,
        "gender": "Female",
        "profession": "PR Officer",
        "education": "BSPR",
        "location": "Faisalabad",
    },
    {
        "name": "Komal",
        "age": 27,
        "gender": "Female",
        "profession": "Counselor",
        "education": "MSc Psychology",
        "location": "Peshawar",
    },
    {
        "name": "Rida",
        "age": 26,
        "gender": "Female",
        "profession": "SEO Specialist",
        "education": "BS IT",
        "location": "Karachi",
    },
    {
        "name": "Javeria",
        "age": 25,
        "gender": "Female",
        "profession": "Researcher",
        "education": "MPhil Biology",
        "location": "Lahore",
    },
    {
        "name": "Shumaila",
        "age": 29,
        "gender": "Female",
        "profession": "Lecturer",
        "education": "M.Ed",
        "location": "Islamabad",
    },
    {
        "name": "Haleema",
        "age": 24,
        "gender": "Female",
        "profession": "Accountant",
        "education": "B.Com",
        "location": "Rawalpindi",
    },
    {
        "name": "Najma",
        "age": 30,
        "gender": "Female",
        "profession": "Fitness Coach",
        "education": "BS Sports Sci",
        "location": "Faisalabad",
    },
    {
        "name": "Rukhsar",
        "age": 28,
        "gender": "Female",
        "profession": "Biochemist",
        "education": "BS Biochemistry",
        "location": "Peshawar",
    },
    {
        "name": "Farah",
        "age": 27,
        "gender": "Female",
        "profession": "QA Engineer",
        "education": "BSSE",
        "location": "Karachi",
    },
    {
        "name": "Ayesha",
        "age": 21,
        "gender": "Female",
        "profession": "Graphic Designer",
        "education": "BFA",
        "location": "Lahore",
    },
    {
        "name": "Misbah",
        "age": 23,
        "gender": "Female",
        "profession": "Content Creator",
        "education": "BS Media",
        "location": "Islamabad",
    },
    {
        "name": "Saima",
        "age": 26,
        "gender": "Female",
        "profession": "Physiotherapist",
        "education": "DPT",
        "location": "Rawalpindi",
    },
    {
        "name": "Sobia",
        "age": 25,
        "gender": "Female",
        "profession": "Event Planner",
        "education": "BBA",
        "location": "Faisalabad",
    },
    {
        "name": "Tahira",
        "age": 27,
        "gender": "Female",
        "profession": "Data Scientist",
        "education": "BS Data Science",
        "location": "Peshawar",
    },
    {
        "name": "Rubab",
        "age": 24,
        "gender": "Female",
        "profession": "Web Developer",
        "education": "BS Web Dev",
        "location": "Karachi",
    },
    {
        "name": "Sehrish",
        "age": 29,
        "gender": "Female",
        "profession": "Marketing Analyst",
        "education": "MBA Marketing",
        "location": "Lahore",
    },
    {
        "name": "Farheen",
        "age": 28,
        "gender": "Female",
        "profession": "Speech Therapist",
        "education": "MS Speech Therapy",
        "location": "Islamabad",
    },
    {
        "name": "Noreen",
        "age": 22,
        "gender": "Female",
        "profession": "Animator",
        "education": "BS Animation",
        "location": "Rawalpindi",
    },
    {
        "name": "Afia",
        "age": 26,
        "gender": "Female",
        "profession": "Civil Engineer",
        "education": "B.E",
        "location": "Faisalabad",
    },
    {
        "name": "Sundus",
        "age": 25,
        "gender": "Female",
        "profession": "Teacher",
        "education": "B.Ed",
        "location": "Peshawar",
    },
    {
        "name": "Arooj",
        "age": 27,
        "gender": "Female",
        "profession": "AI Developer",
        "education": "BSCS",
        "location": "Karachi",
    },
    {
        "name": "Mahrukh",
        "age": 24,
        "gender": "Female",
        "profession": "Journalist",
        "education": "Mass Comm",
        "location": "Lahore",
    },
    {
        "name": "Hania",
        "age": 28,
        "gender": "Female",
        "profession": "HR Specialist",
        "education": "BBA",
        "location": "Islamabad",
    },
    {
        "name": "Samina",
        "age": 29,
        "gender": "Female",
        "profession": "Cybersecurity Expert",
        "education": "MS CyberSec",
        "location": "Rawalpindi",
    },
    {
        "name": "Alishba",
        "age": 23,
        "gender": "Female",
        "profession": "Software Engineer",
        "education": "BSCS",
        "location": "Faisalabad",
    },
    {
        "name": "Safa",
        "age": 26,
        "gender": "Female",
        "profession": "Pharmacist",
        "education": "PharmD",
        "location": "Peshawar",
    },
    {
        "name": "Madiha",
        "age": 25,
        "gender": "Female",
        "profession": "Interior Designer",
        "education": "BID",
        "location": "Karachi",
    },
    {
        "name": "Esha",
        "age": 27,
        "gender": "Female",
        "profession": "Dentist",
        "education": "BDS",
        "location": "Lahore",
    },
    {
        "name": "Tayyaba",
        "age": 24,
        "gender": "Female",
        "profession": "Content Writer",
        "education": "BA English",
        "location": "Islamabad",
    },
    {
        "name": "Zara",
        "age": 28,
        "gender": "Female",
        "profession": "Banker",
        "education": "BBA",
        "location": "Rawalpindi",
    },
    {
        "name": "Mahnoor",
        "age": 29,
        "gender": "Female",
        "profession": "Architect",
        "education": "B.Arch",
        "location": "Faisalabad",
    },
    {
        "name": "Ambreen",
        "age": 26,
        "gender": "Female",
        "profession": "Lecturer",
        "education": "MSc Chemistry",
        "location": "Peshawar",
    },
    {
        "name": "Sumbul",
        "age": 25,
        "gender": "Female",
        "profession": "Nutritionist",
        "education": "BS Nutrition",
        "location": "Karachi",
    },
    {
        "name": "Anila",
        "age": 27,
        "gender": "Female",
        "profession": "Lawyer",
        "education": "LLB",
        "location": "Lahore",
    },
    {
        "name": "Saba",
        "age": 24,
        "gender": "Female",
        "profession": "Social Worker",
        "education": "BA Sociology",
        "location": "Islamabad",
    },
    {
        "name": "Sidra",
        "age": 28,
        "gender": "Female",
        "profession": "Data Analyst",
        "education": "BS Data Science",
        "location": "Rawalpindi",
    },
    {
        "name": "Hina",
        "age": 29,
        "gender": "Female",
        "profession": "UX Designer",
        "education": "BS HCI",
        "location": "Faisalabad",
    },
    {
        "name": "Amina",
        "age": 26,
        "gender": "Female",
        "profession": "Teacher",
        "education": "MA English",
        "location": "Peshawar",
    },
    {
        "name": "Bushra",
        "age": 25,
        "gender": "Female",
        "profession": "Fashion Designer",
        "education": "BFD",
        "location": "Karachi",
    },
    {
        "name": "Naila",
        "age": 27,
        "gender": "Female",
        "profession": "Software Developer",
        "education": "BSSE",
        "location": "Lahore",
    },
    {
        "name": "Sanaa",
        "age": 24,
        "gender": "Female",
        "profession": "Environmentalist",
        "education": "MS Env Sci",
        "location": "Islamabad",
    },
    {
        "name": "Faryal",
        "age": 28,
        "gender": "Female",
        "profession": "Journalist",
        "education": "Mass Comm",
        "location": "Rawalpindi",
    },
    {
        "name": "Zunaira",
        "age": 29,
        "gender": "Female",
        "profession": "Accountant",
        "education": "B.Com",
        "location": "Faisalabad",
    },
    {
        "name": "Roshan",
        "age": 26,
        "gender": "Female",
        "profession": "Graphic Designer",
        "education": "BFA",
        "location": "Peshawar",
    },
    {
        "name": "Iram",
        "age": 25,
        "gender": "Female",
        "profession": "SEO Specialist",
        "education": "BS IT",
        "location": "Karachi",
    },
    {
        "name": "Sadia",
        "age": 27,
        "gender": "Female",
        "profession": "Counselor",
        "education": "MSc Psychology",
        "location": "Lahore",
    },
    {
        "name": "Mehak",
        "age": 24,
        "gender": "Female",
        "profession": "Researcher",
        "education": "MPhil Biology",
        "location": "Islamabad",
    },
    {
        "name": "Saira",
        "age": 28,
        "gender": "Female",
        "profession": "Fitness Coach",
        "education": "BS Sports Sci",
        "location": "Rawalpindi",
    },
    {
        "name": "Nargis",
        "age": 29,
        "gender": "Female",
        "profession": "Biochemist",
        "education": "BS Biochemistry",
        "location": "Faisalabad",
    },
    {
        "name": "Areej",
        "age": 26,
        "gender": "Female",
        "profession": "QA Engineer",
        "education": "BSSE",
        "location": "Peshawar",
    },
    {
        "name": "Huma",
        "age": 25,
        "gender": "Female",
        "profession": "Content Creator",
        "education": "BS Media",
        "location": "Karachi",
    },
    {
        "name": "Sumbal",
        "age": 27,
        "gender": "Female",
        "profession": "Physiotherapist",
        "education": "DPT",
        "location": "Lahore",
    },
    {
        "name": "Naima",
        "age": 24,
        "gender": "Female",
        "profession": "Event Planner",
        "education": "BBA",
        "location": "Islamabad",
    },
    # Male Rishtas (100)
    {
        "name": "Ali",
        "age": 28,
        "gender": "Male",
        "profession": "Software Engineer",
        "education": "BSCS",
        "location": "Karachi",
    },
    {
        "name": "Ahmed",
        "age": 30,
        "gender": "Male",
        "profession": "Banker",
        "education": "MBA",
        "location": "Lahore",
    },
    {
        "name": "Usman",
        "age": 27,
        "gender": "Male",
        "profession": "Doctor",
        "education": "MBBS",
        "location": "Islamabad",
    },
    {
        "name": "Hamza",
        "age": 26,
        "gender": "Male",
        "profession": "Lawyer",
        "education": "LLB",
        "location": "Rawalpindi",
    },
    {
        "name": "Zeeshan",
        "age": 29,
        "gender": "Male",
        "profession": "Civil Engineer",
        "education": "B.E",
        "location": "Faisalabad",
    },
    {
        "name": "Talha",
        "age": 28,
        "gender": "Male",
        "profession": "Accountant",
        "education": "ACCA",
        "location": "Peshawar",
    },
    {
        "name": "Noman",
        "age": 30,
        "gender": "Male",
        "profession": "Professor",
        "education": "PhD",
        "location": "Karachi",
    },
    {
        "name": "Danish",
        "age": 25,
        "gender": "Male",
        "profession": "Pharmacist",
        "education": "PharmD",
        "location": "Lahore",
    },
    {
        "name": "Bilal",
        "age": 26,
        "gender": "Male",
        "profession": "Businessman",
        "education": "BBA",
        "location": "Islamabad",
    },
    {
        "name": "Salman",
        "age": 27,
        "gender": "Male",
        "profession": "Mechanical Engineer",
        "education": "BSME",
        "location": "Rawalpindi",
    },
    {
        "name": "Asad",
        "age": 28,
        "gender": "Male",
        "profession": "Pilot",
        "education": "Aviation",
        "location": "Faisalabad",
    },
    {
        "name": "Rehan",
        "age": 29,
        "gender": "Male",
        "profession": "Marketing Manager",
        "education": "MBA",
        "location": "Peshawar",
    },
    {
        "name": "Saad",
        "age": 30,
        "gender": "Male",
        "profession": "HR Officer",
        "education": "BBA",
        "location": "Karachi",
    },
    {
        "name": "Yasir",
        "age": 26,
        "gender": "Male",
        "profession": "Electrical Engineer",
        "education": "BEE",
        "location": "Lahore",
    },
    {
        "name": "Owais",
        "age": 25,
        "gender": "Male",
        "profession": "Civil Servant",
        "education": "CSS",
        "location": "Islamabad",
    },
    {
        "name": "Rizwan",
        "age": 27,
        "gender": "Male",
        "profession": "Graphic Designer",
        "education": "BFA",
        "location": "Rawalpindi",
    },
    {
        "name": "Shahzaib",
        "age": 28,
        "gender": "Male",
        "profession": "Journalist",
        "education": "Mass Comm",
        "location": "Faisalabad",
    },
    {
        "name": "Moiz",
        "age": 29,
        "gender": "Male",
        "profession": "Economist",
        "education": "MSc Economics",
        "location": "Peshawar",
    },
    {
        "name": "Waqas",
        "age": 30,
        "gender": "Male",
        "profession": "Psychologist",
        "education": "MSc Psychology",
        "location": "Karachi",
    },
    {
        "name": "Fahad",
        "age": 24,
        "gender": "Male",
        "profession": "Data Scientist",
        "education": "BS Data Science",
        "location": "Lahore",
    },
    {
        "name": "Tariq",
        "age": 25,
        "gender": "Male",
        "profession": "Lab Technician",
        "education": "DMLT",
        "location": "Islamabad",
    },
    {
        "name": "Adeel",
        "age": 26,
        "gender": "Male",
        "profession": "Content Writer",
        "education": "BA English",
        "location": "Rawalpindi",
    },
    {
        "name": "Hassan",
        "age": 27,
        "gender": "Male",
        "profession": "Architect",
        "education": "B.Arch",
        "location": "Faisalabad",
    },
    {
        "name": "Imran",
        "age": 28,
        "gender": "Male",
        "profession": "Auditor",
        "education": "CA",
        "location": "Peshawar",
    },
    {
        "name": "Zubair",
        "age": 29,
        "gender": "Male",
        "profession": "Digital Marketer",
        "education": "BS Marketing",
        "location": "Karachi",
    },
    {
        "name": "Shahid",
        "age": 30,
        "gender": "Male",
        "profession": "Fitness Trainer",
        "education": "BS Sports Sci",
        "location": "Lahore",
    },
    {
        "name": "Naveed",
        "age": 26,
        "gender": "Male",
        "profession": "Chef",
        "education": "Diploma Culinary",
        "location": "Islamabad",
    },
    {
        "name": "Arslan",
        "age": 27,
        "gender": "Male",
        "profession": "Librarian",
        "education": "MLIS",
        "location": "Rawalpindi",
    },
    {
        "name": "Umar",
        "age": 28,
        "gender": "Male",
        "profession": "Teacher",
        "education": "MA Urdu",
        "location": "Faisalabad",
    },
    {
        "name": "Ahsan",
        "age": 29,
        "gender": "Male",
        "profession": "Engineer",
        "education": "B.E",
        "location": "Peshawar",
    },
    {
        "name": "Jawad",
        "age": 30,
        "gender": "Male",
        "profession": "Network Admin",
        "education": "BS IT",
        "location": "Karachi",
    },
    {
        "name": "Ammar",
        "age": 25,
        "gender": "Male",
        "profession": "AI Developer",
        "education": "BSCS",
        "location": "Lahore",
    },
    {
        "name": "Junaid",
        "age": 26,
        "gender": "Male",
        "profession": "Video Editor",
        "education": "BFA",
        "location": "Islamabad",
    },
    {
        "name": "Kashif",
        "age": 27,
        "gender": "Male",
        "profession": "Systems Analyst",
        "education": "BSSE",
        "location": "Rawalpindi",
    },
    {
        "name": "Shayan",
        "age": 28,
        "gender": "Male",
        "profession": "Researcher",
        "education": "MPhil Physics",
        "location": "Faisalabad",
    },
    {
        "name": "Rauf",
        "age": 29,
        "gender": "Male",
        "profession": "Game Developer",
        "education": "BS Game Dev",
        "location": "Peshawar",
    },
    {
        "name": "Basit",
        "age": 30,
        "gender": "Male",
        "profession": "Cybersecurity Expert",
        "education": "MS CyberSec",
        "location": "Karachi",
    },
    {
        "name": "Kamran",
        "age": 26,
        "gender": "Male",
        "profession": "UX Designer",
        "education": "BS HCI",
        "location": "Lahore",
    },
    {
        "name": "Irfan",
        "age": 27,
        "gender": "Male",
        "profession": "Translator",
        "education": "MA Arabic",
        "location": "Islamabad",
    },
    {
        "name": "Qasim",
        "age": 28,
        "gender": "Male",
        "profession": "Statistician",
        "education": "MS Stats",
        "location": "Rawalpindi",
    },
    {
        "name": "Waqar",
        "age": 29,
        "gender": "Male",
        "profession": "Biotechnologist",
        "education": "BS Biotech",
        "location": "Faisalabad",
    },
    {
        "name": "Azhar",
        "age": 30,
        "gender": "Male",
        "profession": "Operations Manager",
        "education": "MBA",
        "location": "Peshawar",
    },
    {
        "name": "Naeem",
        "age": 25,
        "gender": "Male",
        "profession": "SEO Specialist",
        "education": "BS IT",
        "location": "Karachi",
    },
    {
        "name": "Taimoor",
        "age": 26,
        "gender": "Male",
        "profession": "Software Tester",
        "education": "BSSE",
        "location": "Lahore",
    },
    {
        "name": "Omar",
        "age": 27,
        "gender": "Male",
        "profession": "Web Developer",
        "education": "BS Web Dev",
        "location": "Islamabad",
    },
    {
        "name": "Haroon",
        "age": 28,
        "gender": "Male",
        "profession": "Statistician",
        "education": "MSc Math",
        "location": "Rawalpindi",
    },
    {
        "name": "Faizan",
        "age": 29,
        "gender": "Male",
        "profession": "DevOps Engineer",
        "education": "BSCS",
        "location": "Faisalabad",
    },
    {
        "name": "Shabbir",
        "age": 30,
        "gender": "Male",
        "profession": "Political Analyst",
        "education": "BS Political Sci",
        "location": "Peshawar",
    },
    {
        "name": "Adnan",
        "age": 25,
        "gender": "Male",
        "profession": "Content Creator",
        "education": "BS Media",
        "location": "Karachi",
    },
    {
        "name": "Arif",
        "age": 26,
        "gender": "Male",
        "profession": "Physiotherapist",
        "education": "DPT",
        "location": "Lahore",
    },
    {
        "name": "Zain",
        "age": 27,
        "gender": "Male",
        "profession": "Event Planner",
        "education": "BBA",
        "location": "Islamabad",
    },
    {
        "name": "Farhan",
        "age": 28,
        "gender": "Male",
        "profession": "Data Analyst",
        "education": "BS Data Science",
        "location": "Rawalpindi",
    },
    {
        "name": "Asim",
        "age": 29,
        "gender": "Male",
        "profession": "Software Engineer",
        "education": "BSCS",
        "location": "Faisalabad",
    },
    {
        "name": "Hammad",
        "age": 30,
        "gender": "Male",
        "profession": "Pharmacist",
        "education": "PharmD",
        "location": "Peshawar",
    },
    {
        "name": "Ibrahim",
        "age": 25,
        "gender": "Male",
        "profession": "Interior Designer",
        "education": "BID",
        "location": "Karachi",
    },
    {
        "name": "Taha",
        "age": 26,
        "gender": "Male",
        "profession": "Dentist",
        "education": "BDS",
        "location": "Lahore",
    },
    {
        "name": "Aqeel",
        "age": 27,
        "gender": "Male",
        "profession": "Content Writer",
        "education": "BA English",
        "location": "Islamabad",
    },
    {
        "name": "Sufyan",
        "age": 28,
        "gender": "Male",
        "profession": "Banker",
        "education": "BBA",
        "location": "Rawalpindi",
    },
    {
        "name": "Muneeb",
        "age": 29,
        "gender": "Male",
        "profession": "Architect",
        "education": "B.Arch",
        "location": "Faisalabad",
    },
    {
        "name": "Waleed",
        "age": 30,
        "gender": "Male",
        "profession": "Lecturer",
        "education": "MSc Chemistry",
        "location": "Peshawar",
    },
    {
        "name": "Zohaib",
        "age": 25,
        "gender": "Male",
        "profession": "Nutritionist",
        "education": "BS Nutrition",
        "location": "Karachi",
    },
    {
        "name": "Daniyal",
        "age": 26,
        "gender": "Male",
        "profession": "Lawyer",
        "education": "LLB",
        "location": "Lahore",
    },
    {
        "name": "Amir",
        "age": 27,
        "gender": "Male",
        "profession": "Social Worker",
        "education": "BA Sociology",
        "location": "Islamabad",
    },
    {
        "name": "Shoaib",
        "age": 28,
        "gender": "Male",
        "profession": "Data Analyst",
        "education": "BS Data Science",
        "location": "Rawalpindi",
    },
    {
        "name": "Umair",
        "age": 29,
        "gender": "Male",
        "profession": "UX Designer",
        "education": "BS HCI",
        "location": "Faisalabad",
    },
    {
        "name": "Bilawal",
        "age": 30,
        "gender": "Male",
        "profession": "Teacher",
        "education": "MA English",
        "location": "Peshawar",
    },
    {
        "name": "Arham",
        "age": 25,
        "gender": "Male",
        "profession": "Fashion Designer",
        "education": "BFD",
        "location": "Karachi",
    },
    {
        "name": "Faisal",
        "age": 26,
        "gender": "Male",
        "profession": "Software Developer",
        "education": "BSSE",
        "location": "Lahore",
    },
    {
        "name": "Rahim",
        "age": 27,
        "gender": "Male",
        "profession": "Environmentalist",
        "education": "MS Env Sci",
        "location": "Islamabad",
    },
    {
        "name": "Sami",
        "age": 28,
        "gender": "Male",
        "profession": "Journalist",
        "education": "Mass Comm",
        "location": "Rawalpindi",
    },
    {
        "name": "Yousuf",
        "age": 29,
        "gender": "Male",
        "profession": "Accountant",
        "education": "B.Com",
        "location": "Faisalabad",
    },
    {
        "name": "Hussain",
        "age": 30,
        "gender": "Male",
        "profession": "Graphic Designer",
        "education": "BFA",
        "location": "Peshawar",
    },
    {
        "name": "Mustafa",
        "age": 25,
        "gender": "Male",
        "profession": "SEO Specialist",
        "education": "BS IT",
        "location": "Karachi",
    },
    {
        "name": "Hamid",
        "age": 26,
        "gender": "Male",
        "profession": "Counselor",
        "education": "MSc Psychology",
        "location": "Lahore",
    },
    {
        "name": "Rayan",
        "age": 27,
        "gender": "Male",
        "profession": "Researcher",
        "education": "MPhil Biology",
        "location": "Islamabad",
    },
    {
        "name": "Ehsan",
        "age": 28,
        "gender": "Male",
        "profession": "Fitness Coach",
        "education": "BS Sports Sci",
        "location": "Rawalpindi",
    },
    {
        "name": "Salah",
        "age": 29,
        "gender": "Male",
        "profession": "Biochemist",
        "education": "BS Biochemistry",
        "location": "Faisalabad",
    },
    {
        "name": "Nasir",
        "age": 30,
        "gender": "Male",
        "profession": "QA Engineer",
        "education": "BSSE",
        "location": "Peshawar",
    },
    {
        "name": "Amin",
        "age": 25,
        "gender": "Male",
        "profession": "Content Creator",
        "education": "BS Media",
        "location": "Karachi",
    },
    {
        "name": "Rameez",
        "age": 26,
        "gender": "Male",
        "profession": "Physiotherapist",
        "education": "DPT",
        "location": "Lahore",
    },
    {
        "name": "Zubair",
        "age": 27,
        "gender": "Male",
        "profession": "Event Planner",
        "education": "BBA",
        "location": "Islamabad",
    },
]
